name : 'Install Nim'
description: 'Install Nim.'

inputs:
  GITHUB_TOKEN:
    description: 'Your GitHub token.'
    required: true
  version:
    description: 'Version of Nim.'
    required: true

runs:
  using: "composite"
  steps:
    - name: Get Date
      id: get-date
      run: echo "date=$(date "+%Y-%m-%d")" >> $GITHUB_OUTPUT
      shell: bash

    - name: Cache choosenim
      id: cache-choosenim
      uses: actions/cache@v3
      with:
        path: ~/.choosenim
        key: ${{ runner.os }}-choosenim-${{ inputs.version }}-${{ steps.get-date.outputs.date }}
        restore-keys: |
          ${{ runner.os }}-choosenim-${{ inputs.version }}-

    - name: Cache nimble
      id: cache-nimble
      uses: actions/cache@v3
      with:
        path: ~/.nimble
        key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
        restore-keys: |
          ${{ runner.os }}-nimble-

    - name: Setup Nim
      uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: ${{ inputs.version }}
        repo-token: ${{ inputs.GITHUB_TOKEN }}
