name: build

on:
  push:
    paths: ['**', '!*.md', '!.github/**', '.github/workflows/build.yml', '.github/workflows/install-nim/action.yml']
    branches: master
  pull_request:
    paths: ['**', '!*.md', '!.github/**', '.github/workflows/build.yml', '.github/workflows/install-nim/action.yml']

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        nim-version: [stable, devel]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    runs-on: ${{ matrix.os }}
    name: Build and test

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Nim
      uses: './.github/workflows/install-nim'
      with:
        version: ${{ matrix.nim-version }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and test
      run: nimble test -y

  build-non-x86:
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
        arch: ['aarch64', 'riscv64', 'ppc64le']

    runs-on: ubuntu-latest
    name: Build and test (stable, ubuntu-devel, ${{ matrix.arch }})

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Cache nimble
      id: cache-nimble
      uses: actions/cache@v3
      with:
        path: ~/.nimble
        key: ${{ matrix.arch }}-nimble-${{ hashFiles('*.nimble') }}
        restore-keys: |
          ${{ matrix.arch }}-nimble-

    - name: Initialize ${{ matrix.arch }} container, build, and test
      uses: uraimo/run-on-arch-action@v2
      with:
        arch: ${{ matrix.arch }}
        distro: ubuntu_devel
        githubToken: ${{ secrets.GITHUB_TOKEN }}

        dockerRunArgs: |
            --volume "$HOME/.nimble:/root/.nimble"

        install: |
          apt-get update -q -y
          apt-get install -q -y nim

        run: |
          export PATH="$PATH:${NIMBLE_DIR:-$HOME/.nimble}/bin"
          nimble test -y
