# Copyright © 2023 Gruruya <gruruya.chi4c@slmails.com>
# SPDX-License-Identifier: AGPL-3.0-only

name: build
## Build and test nimtemplate.
## See also:
## * ./nim-run/action.yml

on:
  push:
    paths: ['nimtemplate.nim', 'nimtemplate.nimble', 'nimtemplate/**.nim', 'tests/**.nim', '.github/workflows/build.yml', '.github/workflows/nim-run/action.yml']
  pull_request:
    paths: ['nimtemplate.nim', 'nimtemplate.nimble', 'nimtemplate/**.nim', 'tests/**.nim', '.github/workflows/build.yml', '.github/workflows/nim-run/action.yml']

jobs:
  build:
    name: Build and test
    strategy:
      fail-fast: false
      matrix:
        nim-version: [stable, devel]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        arch: [x86_64]
        include:
          - arch: 'aarch64'
            os: 'ubuntu-latest'
          - arch: 'riscv64'
            os: 'ubuntu-latest'
          - arch: 'ppc64le'
            os: 'ubuntu-latest'

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Nim, then build and test
      uses: './.github/workflows/nim-run'
      with:
        run: |
          nimble build -y
          nimble test -y
        version: ${{ matrix.nim-version }}
        arch: ${{ matrix.arch }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Artifact
      if: ${{ matrix.os == 'windows-latest' }}
      uses: actions/upload-artifact@v3
      with:
        name: nimtemplate-${{ matrix.os }}-${{ matrix.arch }}.exe
        path: nimtemplate.exe

    - name: Upload Artifact
      if: ${{ matrix.os != 'windows-latest' }}
      uses: actions/upload-artifact@v3
      with:
        name: nimtemplate-${{ matrix.os }}-${{ matrix.arch }}
        path: nimtemplate.out
