name: build

on:
  push:
    paths-ignore: '*.md'
    branches: master
  pull_request:
    paths-ignore: '*.md'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        nim-version: [stable, devel]
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Get Date
      id: get-date
      run: echo "::set-output name=date::$(date "+%Y-%m-%d")"
      shell: bash

    - name: Cache choosenim
      id: cache-choosenim
      uses: actions/cache@v3
      with:
        path: ~/.choosenim
        key: ${{ runner.os }}-choosenim-${{ matrix.nim-version }}-${{ steps.get-date.outputs.date }}
        restore-keys: |
          ${{ runner.os }}-choosenim-${{ matrix.nim-version }}-

    - name: Cache nimble
      id: cache-nimble
      uses: actions/cache@v3
      with:
        path: ~/.nimble
        key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
        restore-keys: |
          ${{ runner.os }}-nimble-

    - uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: ${{ matrix.nim-version }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - run: nimble build -y
    - run: nimble test -y
