# REUSE compliance linter, see https://reuse.software/faq/ --- nimtemplate
# SPDX-FileCopyrightText: 2022 Free Software Foundation Europe e.V. <https://fsfe.org>
# SPDX-License-Identifier: CC0-1.0

name: linting reuse
on: [push, pull_request]

jobs:
  REUSE-Compliance-Check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: fsfe/reuse-action@v1
